# Production
services:
  api:
    image: espresso-api:prod
    build:
      context: ./api
      dockerfile: Dockerfile
      target: production
    develop:
      watch:
        - action: rebuild
          path: ./api
          target: /src
          initial_sync: true
          ignore:
            - node_modules/
    container_name: espresso-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - espresso-network

networks:
  espresso-network:
    driver: bridge
